version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: ./app
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://appuser:changeme@db:5432/appdb
      QB_CLIENT_ID: your_qb_client_id
      QB_CLIENT_SECRET: your_qb_client_secret
      QB_REALM_ID: your_qb_realm_id
      QB_REDIRECT_URI: https://your-domain.com/auth/quickbooks/callback
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  pgdata:
